#!/usr/bin/env python3
"""
Redis Data Parser - Loads and processes Redis command categories
"""

def get_redis_data():
    """Return the complete Redis command and category data for both versions."""
    
    redis_data = {
        'redis7': {
            'categories': {
                'keyspace': ['ttl', 'exists', 'copy', 'unlink', 'persist', 'touch', 'pttl', 'pexpire', 'object|help', 'object|encoding', 'object|idletime', 'object|freq', 'object|refcount', 'flushall', 'renamenx', 'restore', 'scan', 'flushdb', 'expireat', 'keys', 'expire', 'expiretime', 'randomkey', 'pexpireat', 'del', 'dbsize', 'type', 'pexpiretime', 'dump', 'sflush', 'rename'],
                
                'read': ['ttl', 'hvals', 'exists', 'hscan', 'sismember', 'xread', 'xrevrange', 'sintercard', 'zrange', 'zinter', 'zrank', 'sdiff', 'xrange', 'smembers', 'georadiusbymember_ro', 'hstrlen', 'touch', 'zrevrange', 'pttl', 'zrevrangebyscore', 'bitfield_ro', 'lindex', 'httl', 'zunion', 'geodist', 'zlexcount', 'zdiff', 'zrangebylex', 'zcount', 'zrandmember', 'zcard', 'lcs', 'xpending', 'hget', 'get', 'lpos', 'mget', 'hexists', 'object|encoding', 'object|idletime', 'object|freq', 'object|refcount', 'sinter', 'memory|usage', 'bitpos', 'zscan', 'scan', 'zrangebyscore', 'xlen', 'keys', 'llen', 'pfcount', 'hrandfield', 'substr', 'georadius_ro', 'hmget', 'getbit', 'strlen', 'hpexpiretime', 'lrange', 'expiretime', 'randomkey', 'zscore', 'hkeys', 'getrange', 'geopos', 'geosearch', 'sort_ro', 'zrevrangebylex', 'sunion', 'hgetall', 'dbsize', 'type', 'smismember', 'hlen', 'zintercard', 'zrevrank', 'bitcount', 'scard', 'xinfo|stream', 'xinfo|groups', 'xinfo|consumers', 'sscan', 'hexpiretime', 'pexpiretime', 'srandmember', 'dump', 'geohash', 'zmscore', 'hpttl'],
                
                'write': ['sadd', 'linsert', 'georadiusbymember', 'setnx', 'hset', 'hmset', 'lpushx', 'copy', 'setex', 'zrangestore', 'xtrim', 'zremrangebyscore', 'bzpopmax', 'set', 'hincrbyfloat', 'unlink', 'geoadd', 'decr', 'persist', 'zpopmin', 'sinterstore', 'hpersist', 'hexpireat', 'incrby', 'blmove', 'bitfield', 'xack', 'zmpop', 'xautoclaim', 'sdiffstore', 'zremrangebyrank', 'zdiffstore', 'zadd', 'incr', 'hincrby', 'hpexpire', 'getdel', 'blpop', 'lpop', 'hsetnx', 'sort', 'rpush', 'xgroup|createconsumer', 'xgroup|delconsumer', 'xgroup|create', 'xgroup|setid', 'xgroup|destroy', 'pexpire', 'getex', 'ltrim', 'zremrangebylex', 'srem', 'msetnx', 'lmpop', 'psetex', 'lset', 'xsetid', 'rpoplpush', 'flushall', 'renamenx', 'restore', 'flushdb', 'xreadgroup', 'xdel', 'append', 'getset', 'setbit', 'brpoplpush', 'expireat', 'zpopmax', 'hexpire', 'pfadd', 'expire', 'pfmerge', 'xclaim', 'geosearchstore', 'georadius', 'hpexpireat', 'incrbyfloat', 'function|restore', 'function|flush', 'function|load', 'function|delete', 'pexpireat', 'bitop', 'zincrby', 'mset', 'lrem', 'bzmpop', 'xadd', 'rpop', 'sunionstore', 'del', 'zunionstore', 'setrange', 'brpop', 'lmove', 'rpushx', 'zrem', 'lpush', 'zinterstore', 'smove', 'blmpop', 'decrby', 'bzpopmin', 'hdel', 'sflush', 'spop', 'rename'],
                
                'set': ['sadd', 'sismember', 'sintercard', 'sinterstore', 'sdiff', 'smembers', 'sdiffstore', 'sort', 'srem', 'sinter', 'sunionstore', 'sort_ro', 'sunion', 'smismember', 'smove', 'scard', 'sscan', 'srandmember', 'spop'],
                
                'sortedset': ['zrangestore', 'zremrangebyscore', 'bzpopmax', 'zpopmin', 'zrange', 'zinter', 'zrank', 'zmpop', 'zremrangebyrank', 'zdiffstore', 'zadd', 'zrevrange', 'zrevrangebyscore', 'sort', 'zunion', 'zremrangebylex', 'zlexcount', 'zdiff', 'zrangebylex', 'zcount', 'zrandmember', 'zcard', 'zscan', 'zrangebyscore', 'zpopmax', 'zscore', 'zincrby', 'bzmpop', 'sort_ro', 'zrevrangebylex', 'zunionstore', 'zintercard', 'zrem', 'zinterstore', 'zrevrank', 'bzpopmin', 'zmscore'],
                
                'list': ['linsert', 'lpushx', 'blmove', 'blpop', 'lpop', 'sort', 'rpush', 'lindex', 'ltrim', 'lmpop', 'lpos', 'lset', 'rpoplpush', 'brpoplpush', 'llen', 'lrange', 'lrem', 'rpop', 'sort_ro', 'brpop', 'lmove', 'rpushx', 'lpush', 'blmpop'],
                
                'hash': ['hvals', 'hscan', 'hset', 'hmset', 'hincrbyfloat', 'hpersist', 'hexpireat', 'hstrlen', 'hincrby', 'hpexpire', 'hsetnx', 'httl', 'hget', 'hexists', 'hexpire', 'hrandfield', 'hmget', 'hpexpiretime', 'hkeys', 'hpexpireat', 'hgetall', 'hlen', 'hexpiretime', 'hdel', 'hpttl'],
                
                'string': ['setnx', 'setex', 'set', 'decr', 'incrby', 'incr', 'getdel', 'getex', 'msetnx', 'lcs', 'get', 'mget', 'psetex', 'append', 'getset', 'substr', 'strlen', 'getrange', 'incrbyfloat', 'mset', 'setrange', 'decrby'],
                
                'bitmap': ['bitfield', 'bitfield_ro', 'bitpos', 'setbit', 'getbit', 'bitop', 'bitcount'],
                
                'hyperloglog': ['pfadd', 'pfcount', 'pfmerge'],
                
                'geo': ['georadiusbymember', 'geoadd', 'georadiusbymember_ro', 'geodist', 'georadius_ro', 'geosearchstore', 'georadius', 'geopos', 'geosearch', 'geohash'],
                
                'stream': ['xread', 'xrevrange', 'xtrim', 'xack', 'xrange', 'xautoclaim', 'xgroup|createconsumer', 'xgroup|delconsumer', 'xgroup|create', 'xgroup|help', 'xgroup|setid', 'xgroup|destroy', 'xpending', 'xsetid', 'xreadgroup', 'xdel', 'xlen', 'xclaim', 'xadd', 'xinfo|stream', 'xinfo|help', 'xinfo|groups', 'xinfo|consumers'],
                
                'pubsub': ['publish', 'spublish', 'unsubscribe', 'ssubscribe', 'psubscribe', 'pubsub|channels', 'pubsub|shardnumsub', 'pubsub|numpat', 'pubsub|shardchannels', 'pubsub|numsub', 'subscribe', 'punsubscribe', 'sunsubscribe'],
                
                'admin': ['module|list', 'cluster|set-config-epoch', 'slowlog|get', 'slowlog|reset', 'slowlog|len', 'monitor', 'config|get', 'config|resetstat', 'config|rewrite', 'config|set', 'acl|setuser', 'acl|load', 'acl|users', 'acl|list', 'acl|save', 'acl|getuser', 'acl|log', 'acl|deluser', 'client|kill', 'client|list', 'client|unblock'],
                
                'fast': ['ttl', 'sadd', 'setnx', 'exists', 'publish', 'spublish', 'hset', 'hmset', 'sismember', 'lpushx', 'bzpopmax', 'hincrbyfloat', 'unlink', 'decr', 'persist', 'zpopmin', 'hpersist', 'hexpireat', 'incrby', 'zrank', 'xack', 'xautoclaim', 'hstrlen', 'zadd', 'incr', 'hincrby', 'time', 'hpexpire', 'getdel', 'touch', 'pttl', 'lpop', 'hsetnx', 'bitfield_ro', 'rpush', 'httl', 'pexpire', 'getex', 'zlexcount', 'reset', 'select', 'zcount', 'srem', 'zcard', 'hget', 'get', 'mget', 'hexists', 'auth', 'xsetid', 'hello', 'renamenx', 'multi', 'xdel', 'append', 'getset', 'xlen', 'expireat', 'llen', 'zpopmax', 'hexpire', 'pfadd', 'expire', 'echo', 'hmget', 'getbit', 'strlen', 'hpexpiretime', 'expiretime', 'xclaim', 'zscore', 'hpexpireat', 'incrbyfloat', 'pexpireat', 'zincrby', 'xadd', 'rpop', 'watch', 'dbsize', 'type', 'rpushx', 'smismember', 'hlen', 'zrem', 'lpush', 'zrevrank', 'discard', 'smove', 'scard', 'unwatch', 'hexpiretime', 'pexpiretime', 'decrby', 'bzpopmin', 'quit', 'ping', 'hdel', 'spop', 'zmscore', 'hpttl'],
                
                'slow': ['hvals', 'linsert', 'georadiusbymember', 'hscan', 'copy', 'evalsha_ro', 'xread', 'setex', 'zrangestore', 'unsubscribe', 'xrevrange', 'xtrim', 'zremrangebyscore', 'set', 'sintercard', 'geoadd', 'sinterstore', 'ssubscribe', 'zrange', 'zinter', 'blmove', 'sdiff', 'bitfield', 'xrange', 'zmpop', 'smembers', 'sdiffstore', 'zremrangebyrank', 'georadiusbymember_ro', 'zdiffstore', 'eval', 'exec', 'blpop', 'zrevrange', 'zrevrangebyscore', 'sort', 'lindex', 'xgroup', 'xgroup|createconsumer', 'xgroup|delconsumer', 'xgroup|create', 'xgroup|help', 'xgroup|setid', 'xgroup|destroy', 'ltrim', 'zunion', 'zremrangebylex', 'geodist', 'zdiff', 'zrangebylex', 'zrandmember', 'msetnx', 'lcs', 'xpending', 'lmpop', 'module', 'module|list', 'command', 'command|help', 'command|list', 'command|info', 'command|count', 'command|getkeys', 'command|docs', 'command|getkeysandflags', 'lpos', 'psetex', 'cluster', 'cluster|set-config-epoch', 'cluster|keyslot', 'cluster|nodes', 'cluster|slots', 'cluster|shards', 'cluster|myshardid', 'cluster|help', 'cluster|info', 'lset', 'object', 'object|help', 'object|encoding', 'object|idletime', 'object|freq', 'object|refcount', 'sinter', 'memory', 'memory|help', 'memory|usage', 'rpoplpush', 'bitpos', 'evalsha', 'flushall', 'zscan', 'restore', 'scan', 'flushdb', 'xreadgroup', 'slowlog', 'slowlog|help', 'slowlog|get', 'slowlog|reset', 'slowlog|len', 'zrangebyscore', 'setbit', 'brpoplpush', 'monitor', 'config', 'config|help', 'config|get', 'config|resetstat', 'config|rewrite', 'config|set', 'keys', 'acl', 'acl|whoami', 'acl|help', 'acl|setuser', 'acl|cat', 'acl|load', 'acl|users', 'acl|list', 'acl|save', 'acl|getuser', 'acl|genpass', 'acl|log', 'acl|deluser', 'pfcount', 'info', 'hrandfield', 'substr', 'pfmerge', 'georadius_ro', 'lrange', 'psubscribe', 'randomkey', 'hkeys', 'getrange', 'geosearchstore', 'georadius', 'function', 'function|dump', 'function|help', 'function|kill', 'function|restore', 'function|list', 'function|flush', 'function|load', 'function|delete', 'bitop', 'fcall_ro', 'geopos', 'mset', 'lrem', 'geosearch', 'bzmpop', 'sunionstore', 'del', 'sort_ro', 'zrevrangebylex', 'sunion', 'zunionstore', 'hgetall', 'setrange', 'brpop', 'lmove', 'waitaof', 'zintercard', 'pubsub', 'pubsub|help', 'pubsub|channels', 'pubsub|shardnumsub', 'pubsub|numpat', 'pubsub|shardchannels', 'pubsub|numsub', 'zinterstore', 'script', 'script|help', 'script|flush', 'script|debug', 'script|kill', 'script|load', 'script|exists', 'bitcount', 'eval_ro', 'client', 'client|getname', 'client|setinfo', 'client|no-touch', 'client|setname', 'client|kill', 'client|help', 'client|info', 'client|id', 'client|list', 'client|unblock', 'xinfo', 'xinfo|stream', 'xinfo|help', 'xinfo|groups', 'xinfo|consumers', 'sscan', 'wait', 'blmpop', 'subscribe', 'fcall', 'srandmember', 'dump', 'punsubscribe', 'geohash', 'sflush', 'rename', 'sunsubscribe'],
                
                'blocking': ['xread', 'bzpopmax', 'blmove', 'blpop', 'xreadgroup', 'brpoplpush', 'bzmpop', 'brpop', 'waitaof', 'wait', 'blmpop', 'bzpopmin'],
                
                'dangerous': ['sort', 'module|list', 'cluster|set-config-epoch', 'flushall', 'restore', 'flushdb', 'slowlog|get', 'slowlog|reset', 'slowlog|len', 'monitor', 'config|get', 'config|resetstat', 'config|rewrite', 'config|set', 'keys', 'acl|setuser', 'acl|load', 'acl|users', 'acl|list', 'acl|save', 'acl|getuser', 'acl|log', 'acl|deluser', 'info', 'sort_ro', 'client|kill', 'client|list', 'client|unblock', 'sflush'],
                
                'connection': ['reset', 'select', 'command', 'command|help', 'command|list', 'command|info', 'command|count', 'command|getkeys', 'command|docs', 'command|getkeysandflags', 'auth', 'hello', 'echo', 'waitaof', 'client|getname', 'client|setinfo', 'client|no-touch', 'client|setname', 'client|kill', 'client|help', 'client|info', 'client|id', 'client|list', 'client|unblock', 'wait', 'quit', 'ping'],
                
                'transaction': ['exec', 'multi', 'watch', 'discard', 'unwatch'],
                
                'scripting': ['evalsha_ro', 'eval', 'evalsha', 'function|dump', 'function|help', 'function|kill', 'function|restore', 'function|list', 'function|flush', 'function|load', 'function|delete', 'fcall_ro', 'script|help', 'script|flush', 'script|debug', 'script|kill', 'script|load', 'script|exists', 'eval_ro', 'fcall']
            },
            'commands': {}
        },
        
        'redis8': {
            'categories': {
                'keyspace': ['scan', 'rename', 'pexpire', 'pexpireat', 'copy', 'flushdb', 'touch', 'renamenx', 'pexpiretime', 'exists', 'keys', 'pttl', 'persist', 'expireat', 'randomkey', 'dump', 'object|idletime', 'object|encoding', 'object|freq', 'object|help', 'object|refcount', 'del', 'sflush', 'restore', 'ttl', 'expire', 'type', 'expiretime', 'flushall', 'unlink', 'dbsize'],
                
                'read': ['scan', 'zintercard', 'sintercard', 'json.mget', 'cf.compact', 'tdigest.byrevrank', 'bitcount', 'tdigest.revrank', 'json.objkeys', 'tdigest.info', 'ts.mrange', 'ft.sugget', 'sunion', 'ts.mget', 'json.objlen', 'ft.mget', 'xpending', 'tdigest.quantile', 'bf.info', 'pfcount', 'zrange', 'bf.card', 'json.strlen', 'hscan', 'tdigest.min', 'zcount', 'cms.query', 'zrevrangebylex', 'hrandfield', 'json.arrlen', 'srandmember', 'ts.info', 'geopos', 'ts.range', 'tdigest.rank', 'getbit', 'xread', 'touch', 'hexists', 'strlen', 'cms.info', 'georadius_ro', 'xrevrange', 'ft.suglen', 'geohash', 'scard', 'cf.scandump', 'ft.profile', 'pexpiretime', 'cf.mexists', 'geodist', 'exists', 'zrevrange', 'bf.mexists', 'lindex', 'hstrlen', 'xinfo|consumers', 'xinfo|stream', 'xinfo|groups', 'ts.revrange', 'substr', 'hgetall', 'sscan', 'httl', 'keys', 'lpos', 'zcard', 'hget', 'zinter', 'tdigest.max', 'pttl', 'topk.info', 'hpexpiretime', 'bf.exists', 'bitfield_ro', 'llen', 'randomkey', 'cf.exists', 'ft.cursor', 'dump', 'zscan', 'ft.search', 'json.resp', 'sdiff', 'lrange', 'zunion', 'xlen', 'ts.queryindex', 'lcs', 'zmscore', 'tdigest.trimmed_mean', 'ft.aggregate', 'georadiusbymember_ro', 'zrevrangebyscore', 'zrank', 'hmget', 'bf.scandump', 'json.debug', 'object|idletime', 'object|encoding', 'object|freq', 'object|refcount', 'sinter', 'xrange', 'zdiff', 'ts.mrevrange', 'zrangebyscore', 'topk.count', 'getrange', 'ft.get', 'hvals', 'smembers', 'sort_ro', 'zrandmember', 'cf.debug', 'tdigest.cdf', 'ttl', 'ts.get', 'hexpiretime', 'sismember', 'geosearch', 'zrevrank', 'cf.info', 'cf.count', 'zrangebylex', 'zlexcount', 'bf.debug', 'bitpos', 'json.arrindex', 'mget', 'type', 'expiretime', 'json.get', 'json.type', 'hlen', 'zscore', 'memory|usage', 'topk.query', 'tdigest.byrank', 'smismember', 'topk.list', 'hpttl', 'get', 'ft.tagvals', 'dbsize', 'hkeys'],
                
                'write': ['ts.alter', 'rename', 'xsetid', 'incr', 'incrbyfloat', 'pexpire', 'lpush', 'cf.addnx', 'bitop', 'pexpireat', 'cms.incrby', 'json.forget', 'geosearchstore', 'cf.reserve', 'bzmpop', 'hincrby', 'lpop', 'cf.del', 'cf.loadchunk', 'json.set', 'json.merge', 'georadiusbymember', 'ft.sugdel', 'flushdb', 'zmpop', 'json.strappend', 'ft.sugadd', 'setbit', 'ft._dropifx', 'bf.add', 'zpopmax', 'xtrim', 'hdel', 'hexpireat', 'cf.insertnx', 'json.arrappend', 'function|flush', 'function|load', 'function|delete', 'function|restore', 'append', 'decr', 'hpersist', 'bf.loadchunk', 'zremrangebyscore', 'renamenx', 'xadd', 'hpexpireat', 'zadd', 'zrem', 'cf.add', 'geoadd', 'json.nummultby', 'msetnx', 'hsetnx', 'ts.createrule', 'rpushx', 'xautoclaim', 'persist', 'xclaim', 'setrange', 'expireat', 'hincrbyfloat', 'blmpop', 'ltrim', 'getdel', 'brpoplpush', 'hset', 'zremrangebyrank', 'tdigest.merge', 'zdiffstore', 'decrby', 'lmpop', 'zremrangebylex', 'xdel', 'cms.merge', 'json.mset', 'srem', 'sunionstore', 'rpoplpush', 'json.numpowby', 'ft._dropindexifx', 'sdiffstore', 'ts.incrby', 'bf.insert', 'ts.add', 'ts.create', 'hgetdel', 'lset', 'setnx', 'del', 'ts.deleterule', 'ft.safeadd', 'sadd', 'json.del', 'cf.insert', 'blmove', 'getset', 'ft.drop', 'linsert', 'topk.incrby', 'hpexpire', 'ts.decrby', 'rpush', 'json.clear', 'hgetex', 'sflush', 'zincrby', 'bzpopmax', 'rpop', 'zrangestore', 'restore', 'hexpire', 'bf.reserve', 'tdigest.reset', 'lmove', 'ts.del', 'ft.del', 'smove', 'psetex', 'expire', 'setex', 'tdigest.add', 'topk.add', 'sort', 'set', 'topk.reserve', 'incrby', 'bzpopmin', 'xgroup|create', 'xgroup|createconsumer', 'xgroup|destroy', 'xgroup|setid', 'xgroup|delconsumer', 'json.arrinsert', 'zinterstore', 'bitfield', 'brpop', 'zunionstore', 'cms.initbydim', 'pfmerge', 'hmset', 'ft.add', 'xack', 'getex', 'pfadd', 'tdigest.create', 'xreadgroup', 'bf.madd', 'hsetex', 'flushall', 'blpop', 'ts.madd', 'ft.dropindex', 'json.arrtrim', 'lrem', 'cms.initbyprob', 'georadius', 'zpopmin', 'json.arrpop', 'json.toggle', 'unlink', 'spop', 'sinterstore', 'json.numincrby', 'lpushx', 'mset', 'copy'],
                
                'set': ['sintercard', 'sunion', 'srandmember', 'scard', 'sscan', 'sdiff', 'srem', 'sunionstore', 'sdiffstore', 'sinter', 'sadd', 'smembers', 'sort_ro', 'smove', 'sismember', 'sort', 'smismember', 'spop', 'sinterstore'],
                
                'sortedset': ['zintercard', 'bzmpop', 'zrange', 'zcount', 'zrevrangebylex', 'zmpop', 'zpopmax', 'zremrangebyscore', 'zadd', 'zrem', 'zrevrange', 'zcard', 'zinter', 'zscan', 'zremrangebyrank', 'zdiffstore', 'zremrangebylex', 'zunion', 'zmscore', 'zrevrangebyscore', 'zrank', 'zdiff', 'zrangebyscore', 'zincrby', 'sort_ro', 'bzpopmax', 'zrandmember', 'zrangestore', 'sort', 'zrevrank', 'bzpopmin', 'zinterstore', 'zrangebylex', 'zlexcount', 'zunionstore', 'zscore', 'zpopmin'],
                
                'list': ['lpush', 'lpop', 'lindex', 'lpos', 'rpushx', 'blmpop', 'ltrim', 'llen', 'brpoplpush', 'lmpop', 'lrange', 'rpoplpush', 'lset', 'blmove', 'linsert', 'rpush', 'sort_ro', 'rpop', 'lmove', 'sort', 'brpop', 'blpop', 'lrem', 'lpushx'],
                
                'hash': ['hincrby', 'hscan', 'hrandfield', 'hdel', 'hexpireat', 'hexists', 'hpersist', 'hpexpireat', 'hstrlen', 'hsetnx', 'hgetall', 'httl', 'hget', 'hpexpiretime', 'hincrbyfloat', 'hset', 'hgetdel', 'hmget', 'hpexpire', 'hvals', 'hgetex', 'hexpire', 'hexpiretime', 'hmset', 'hsetex', 'hlen', 'hpttl', 'hkeys'],
                
                'string': ['incr', 'incrbyfloat', 'strlen', 'append', 'decr', 'msetnx', 'substr', 'setrange', 'getdel', 'decrby', 'lcs', 'setnx', 'getset', 'getrange', 'psetex', 'setex', 'set', 'incrby', 'mget', 'getex', 'get', 'mset'],
                
                'bitmap': ['bitcount', 'bitop', 'setbit', 'getbit', 'bitfield_ro', 'bitfield', 'bitpos'],
                
                'hyperloglog': ['pfcount', 'pfmerge', 'pfadd'],
                
                'geo': ['geosearchstore', 'georadiusbymember', 'geopos', 'georadius_ro', 'geohash', 'geodist', 'geoadd', 'georadiusbymember_ro', 'geosearch', 'georadius'],
                
                'stream': ['xsetid', 'xpending', 'xtrim', 'xread', 'xrevrange', 'xadd', 'xinfo|consumers', 'xinfo|stream', 'xinfo|help', 'xinfo|groups', 'xautoclaim', 'xclaim', 'xdel', 'xlen', 'xrange', 'xgroup|create', 'xgroup|createconsumer', 'xgroup|destroy', 'xgroup|setid', 'xgroup|help', 'xgroup|delconsumer', 'xack', 'xreadgroup'],
                
                'pubsub': ['publish', 'unsubscribe', 'pubsub|numpat', 'pubsub|shardnumsub', 'pubsub|shardchannels', 'pubsub|numsub', 'pubsub|channels', 'spublish', 'ssubscribe', 'punsubscribe', 'psubscribe', 'subscribe', 'sunsubscribe'],
                
                'admin': ['monitor', 'client|kill', 'client|unblock', 'client|list', 'ft._list', 'slowlog|reset', 'slowlog|len', 'slowlog|get', 'acl|deluser', 'acl|users', 'acl|load', 'acl|setuser', 'acl|log', 'acl|save', 'acl|getuser', 'acl|list', 'config|get', 'config|set', 'config|resetstat', 'config|rewrite', 'cluster|set-config-epoch', 'module|list'],
                
                'fast': ['time', 'echo', 'auth', 'publish', 'xsetid', 'incr', 'tdigest.byrevrank', 'tdigest.revrank', 'incrbyfloat', 'pexpire', 'tdigest.info', 'lpush', 'pexpireat', 'cf.reserve', 'hincrby', 'lpop', 'tdigest.quantile', 'bf.info', 'bf.card', 'hello', 'tdigest.min', 'zcount', 'discard', 'ts.info', 'zpopmax', 'hdel', 'hexpireat', 'tdigest.rank', 'getbit', 'touch', 'hexists', 'strlen', 'append', 'decr', 'multi', 'cms.info', 'hpersist', 'ping', 'renamenx', 'scard', 'xadd', 'hpexpireat', 'watch', 'zadd', 'pexpiretime', 'zrem', 'exists', 'spublish', 'hstrlen', 'hsetnx', 'select', 'httl', 'zcard', 'rpushx', 'hget', 'xautoclaim', 'tdigest.max', 'pttl', 'topk.info', 'hpexpiretime', 'persist', 'xclaim', 'expireat', 'hincrbyfloat', 'bitfield_ro', 'llen', 'getdel', 'hset', 'decrby', 'xdel', 'xlen', 'srem', 'zmscore', 'ts.create', 'hgetdel', 'zrank', 'setnx', 'hmget', 'ts.deleterule', 'sadd', 'getset', 'hpexpire', 'rpush', 'hgetex', 'zincrby', 'bzpopmax', 'rpop', 'tdigest.cdf', 'hexpire', 'bf.reserve', 'tdigest.reset', 'ttl', 'ts.get', 'unwatch', 'smove', 'expire', 'hexpiretime', 'sismember', 'topk.reserve', 'incrby', 'zrevrank', 'bzpopmin', 'cf.info', 'zlexcount', 'cms.initbydim', 'hmset', 'mget', 'xack', 'getex', 'type', 'pfadd', 'expiretime', 'tdigest.create', 'reset', 'hsetex', 'hlen', 'zscore', 'cms.initbyprob', 'tdigest.byrank', 'zpopmin', 'smismember', 'hpttl', 'get', 'unlink', 'spop', 'quit', 'dbsize', 'lpushx'],
                
                'slow': ['scan', 'zintercard', 'rename', 'sintercard', 'bitcount', 'bitop', 'geosearchstore', 'sunion', 'monitor', 'unsubscribe', 'evalsha_ro', 'client', 'client|help', 'client|setname', 'client|getname', 'client|kill', 'client|setinfo', 'client|unblock', 'client|info', 'client|no-touch', 'client|id', 'client|list', 'bzmpop', 'script', 'script|flush', 'script|load', 'script|kill', 'script|debug', 'script|exists', 'script|help', 'pubsub', 'pubsub|numpat', 'pubsub|shardnumsub', 'pubsub|shardchannels', 'pubsub|numsub', 'pubsub|help', 'pubsub|channels', 'waitaof', 'xpending', 'pfcount', 'copy', 'zrange', 'ft._list', 'eval_ro', 'hscan', 'slowlog', 'slowlog|reset', 'slowlog|len', 'slowlog|help', 'slowlog|get', 'georadiusbymember', 'flushdb', 'zrevrangebylex', 'zmpop', 'hrandfield', 'srandmember', 'command', 'command|getkeys', 'command|count', 'command|getkeysandflags', 'command|docs', 'command|info', 'command|help', 'command|list', 'geopos', 'setbit', 'ft._dropifx', 'xtrim', 'xread', 'function', 'function|flush', 'function|load', 'function|help', 'function|delete', 'function|kill', 'function|restore', 'function|dump', 'function|list', 'georadius_ro', 'xrevrange', 'geohash', 'zremrangebyscore', 'geodist', 'zrevrange', 'geoadd', 'lindex', 'acl', 'acl|deluser', 'acl|users', 'acl|whoami', 'acl|load', 'acl|setuser', 'acl|help', 'acl|log', 'acl|save', 'acl|getuser', 'acl|genpass', 'acl|cat', 'acl|list', 'msetnx', 'xinfo', 'xinfo|consumers', 'xinfo|stream', 'xinfo|help', 'xinfo|groups', 'substr', 'hgetall', 'sscan', 'keys', 'lpos', 'zinter', 'wait', 'setrange', 'ssubscribe', 'config', 'config|get', 'config|set', 'config|resetstat', 'config|help', 'config|rewrite', 'blmpop', 'fcall', 'ltrim', 'randomkey', 'dump', 'zscan', 'brpoplpush', 'punsubscribe', 'zremrangebyrank', 'zdiffstore', 'lmpop', 'sdiff', 'zremrangebylex', 'lrange', 'zunion', 'exec', 'sunionstore', 'lcs', 'rpoplpush', 'ft._dropindexifx', 'sdiffstore', 'cluster', 'cluster|help', 'cluster|nodes', 'cluster|keyslot', 'cluster|slots', 'cluster|myshardid', 'cluster|info', 'cluster|shards', 'cluster|set-config-epoch', 'georadiusbymember_ro', 'module', 'module|list', 'zrevrangebyscore', 'lset', 'object', 'object|idletime', 'object|encoding', 'object|freq', 'object|help', 'object|refcount', 'sinter', 'del', 'xrange', 'blmove', 'ft.drop', 'linsert', 'zdiff', 'zrangebyscore', 'getrange', 'hvals', 'sflush', 'eval', 'smembers', 'sort_ro', 'zrandmember', 'psubscribe', 'zrangestore', 'restore', 'lmove', 'evalsha', 'psetex', 'setex', 'sort', 'geosearch', 'set', 'subscribe', 'xgroup', 'xgroup|create', 'xgroup|createconsumer', 'xgroup|destroy', 'xgroup|setid', 'xgroup|help', 'xgroup|delconsumer', 'zinterstore', 'bitfield', 'zrangebylex', 'brpop', 'zunionstore', 'sunsubscribe', 'bitpos', 'pfmerge', 'xreadgroup', 'fcall_ro', 'flushall', 'blpop', 'ft.dropindex', 'memory', 'memory|usage', 'memory|help', 'lrem', 'georadius', 'info', 'sinterstore', 'ft.tagvals', 'hkeys', 'mset'],
                
                'blocking': ['bzmpop', 'waitaof', 'xread', 'wait', 'blmpop', 'brpoplpush', 'blmove', 'bzpopmax', 'bzpopmin', 'brpop', 'xreadgroup', 'blpop'],
                
                'dangerous': ['monitor', 'client|kill', 'client|unblock', 'client|list', 'slowlog|reset', 'slowlog|len', 'slowlog|get', 'flushdb', 'ft._dropifx', 'acl|deluser', 'acl|users', 'acl|load', 'acl|setuser', 'acl|log', 'acl|save', 'acl|getuser', 'acl|list', 'keys', 'config|get', 'config|set', 'config|resetstat', 'config|rewrite', 'ft._dropindexifx', 'cluster|set-config-epoch', 'module|list', 'ft.drop', 'sflush', 'sort_ro', 'restore', 'sort', 'flushall', 'ft.dropindex', 'info', 'ft.tagvals'],
                
                'connection': ['echo', 'auth', 'client|help', 'client|setname', 'client|getname', 'client|kill', 'client|setinfo', 'client|unblock', 'client|info', 'client|no-touch', 'client|id', 'client|list', 'waitaof', 'hello', 'command', 'command|getkeys', 'command|count', 'command|getkeysandflags', 'command|docs', 'command|info', 'command|help', 'command|list', 'ping', 'select', 'wait', 'reset', 'quit'],
                
                'transaction': ['discard', 'multi', 'watch', 'exec', 'unwatch'],
                
                'scripting': ['evalsha_ro', 'script|flush', 'script|load', 'script|kill', 'script|debug', 'script|exists', 'script|help', 'eval_ro', 'function|flush', 'function|load', 'function|help', 'function|delete', 'function|kill', 'function|restore', 'function|dump', 'function|list', 'fcall', 'eval', 'evalsha', 'fcall_ro'],
                
                # Redis 8 additional module categories
                'json': ['json.mget', 'json.objkeys', 'json.forget', 'json.objlen', 'json.strlen', 'json.set', 'json.merge', 'json.strappend', 'json.arrlen', 'json.arrappend', 'json.nummultby', 'json.resp', 'json.mset', 'json.numpowby', 'json.debug', 'json.del', 'json.clear', 'json.arrinsert', 'json.arrindex', 'json.get', 'json.type', 'json.arrtrim', 'json.arrpop', 'json.toggle', 'json.numincrby'],
                
                'timeseries': ['ts.alter', 'ts.mrange', 'ts.mget', 'ts.info', 'ts.range', 'ts.revrange', 'ts.createrule', 'ts.queryindex', 'ts.incrby', 'ts.add', 'ts.create', 'ts.deleterule', 'ts.mrevrange', 'ts.decrby', 'ts.del', 'ts.get', 'ts.madd'],
                
                'search': ['ft._createifnx', 'ft.synupdate', 'ft.sugget', 'ft.synadd', 'ft.mget', 'ft._list', 'ft.sugdel', 'ft.sugadd', 'ft._dropifx', 'ft.dictdump', 'ft.suglen', 'ft.profile', 'ft.syndump', 'ft.alter', 'ft.aliasupdate', 'ft.aliasadd', 'ft.cursor', 'ft._alterifnx', 'ft.aliasdel', 'ft.search', 'ft.dictadd', 'ft.dictdel', 'ft._dropindexifx', 'ft.aggregate', 'ft.safeadd', 'ft.drop', 'ft.get', 'ft._aliasdelifx', 'ft.del', 'ft.explaincli', 'ft.spellcheck', 'ft._aliasaddifnx', 'ft.create', 'ft.add', 'ft.info', 'ft.explain', 'ft.dropindex', 'ft.tagvals'],
                
                'bloom': ['bf.info', 'bf.card', 'bf.add', 'bf.loadchunk', 'bf.mexists', 'bf.exists', 'bf.insert', 'bf.scandump', 'bf.reserve', 'bf.debug', 'bf.madd'],
                
                'cuckoo': ['cf.compact', 'cf.addnx', 'cf.reserve', 'cf.del', 'cf.loadchunk', 'cf.insertnx', 'cf.scandump', 'cf.mexists', 'cf.add', 'cf.exists', 'cf.insert', 'cf.debug', 'cf.info', 'cf.count'],
                
                'cms': ['cms.incrby', 'cms.query', 'cms.info', 'cms.merge', 'cms.initbydim', 'cms.initbyprob'],
                
                'topk': ['topk.info', 'topk.incrby', 'topk.count', 'topk.add', 'topk.reserve', 'topk.query', 'topk.list'],
                
                'tdigest': ['tdigest.byrevrank', 'tdigest.revrank', 'tdigest.info', 'tdigest.quantile', 'tdigest.min', 'tdigest.rank', 'tdigest.max', 'tdigest.merge', 'tdigest.trimmed_mean', 'tdigest.cdf', 'tdigest.reset', 'tdigest.add', 'tdigest.create', 'tdigest.byrank']
            },
            'commands': {}
        }
    }
    
    return redis_data


def build_command_indexes(redis_data):
    """Build reverse indexes for fast command -> category lookups."""
    for version in redis_data:
        redis_data[version]['commands'] = {}
        for category, commands in redis_data[version]['categories'].items():
            for command in commands:
                # All commands should already be lowercase, but ensure consistency
                cmd_lower = command.lower()
                if cmd_lower not in redis_data[version]['commands']:
                    redis_data[version]['commands'][cmd_lower] = []
                redis_data[version]['commands'][cmd_lower].append(category)
    
    return redis_data